export enum CancellationStatus {
  PENDING_REVIEW = 'PENDING_REVIEW',
  RESOLVED_REFUND_FULL = 'RESOLVED_REFUND_FULL',
  RESOLVED_REFUND_PARTIAL = 'RESOLVED_REFUND_PARTIAL',
  RESOLVED_NO_REFUND = 'RESOLVED_NO_REFUND',
}
