// booking-status.enum.ts

export enum BookingStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  NEGOTIATING = 'NEGOTIATING',
  FINAL_OFFER_SENT = 'FINAL_OFFER_SENT',
  ACCEPTED = 'ACCEPTED',
  CONTRACT_SIGNED = 'CONTRACT_SIGNED',
  PAID_PARTIAL = 'PAID_PARTIAL',
  PAID_FULL = 'PAID_FULL',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  CANCELLED_PENDING_REVIEW = 'CANCELLED_PENDING_REVIEW',
}
